[Settings]
show = 1
smoothing = 3
fps_lock = 30
gpu_acceleration = 1

[Gestures]
velocity_threshold = 100
cooldown_gesture_const = 0.5
lm_history_len = 5

[Pointer]
pointer_sensitivity = 800
deadzone = 0.05
